site_name:        GenieCache.jl
repo_url:         https://github.com/GenieFramework/GenieCache.jl
site_description: Caching support for Genie.jl
site_author:      Adrian Salceanu

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
